---
spring:
  jpa:
    hibernate.ddl-auto: update
    show_sql: false
---
spring.profiles: local
spring:
  datasource:
    url: jdbc:h2:mem:DEMO
    username: sa
    password:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
---
spring.profiles: cloudfoundry
spring:
  datasource:
    url: ${vcap.services.cleardb.credentials.jdbcUrl}
    username: ${vcap.services.cleardb.credentials.username}
    password: ${vcap.services.cleardb.credentials.password}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
