---
spring:
  jpa:
    hibernate.ddl-auto: update
    show_sql: false
---
# Local profile used for labtop demo
spring.profiles: local
spring:
  datasource:
    url: jdbc:h2:mem:DEMO
    username: sa
    password:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
---
# Profile used when app deployed on Cloudfoundry
spring.profiles: cloudfoundry
spring:
  datasource:
    url: ${vcap.services.cleardb.credentials.jdbcUrl}
    username: ${vcap.services.cleardb.credentials.username}
    password: ${vcap.services.cleardb.credentials.password}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
---
# Profile used when app deployed on OpenShift
spring.profiles: openshift
spring:
  datasource:
    url: jdbc:mysql://${db.host}:3306/${db.name}
    username: ${db.user}
    password: ${db.password}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect